load tmpfile.mat

[B, hfigure2] = soundrecognition('SoundFile', soundfile, 'OtherChoiceFile', otherchoicefile,...
                    'TagName', tagNameStr, 'TagChoice', textTag, 'RightChoice', rightChoiceIdx, ...
                    'Soundtype', SoundType);